import { Manrope } from "next/font/google";
import "./styles.css";

import StyledComponentsRegistry from "@/components/StyledComponentsRegistry";
import Header from "@/components/Header";

export const metadata = {
  title: "Audiophile ecommerce",
  description: "Generated by create next app",
};

const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <StyledComponentsRegistry>
          <Header />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
